### ISSUE TITLE
change Readme.md to reflect changes made to patches.sh since

### ISSUE THREAD

**Issue by MaxBrandtner** [VGPU-Community-Drivers/vGPU-Unlock-patcher#13]
The process described in the Readme file regarding editing the file to have accurate IDs seems to be outdated(within the project). The patch. sh file now seems to have all the option listed within it so all that is needed to be done by the user is to remove the unnecessary lines. Note that this could also be automated using lspci to obtain the name of the GPU. I wonder how this would work out on a system with multiple nvidia GPUs from different architectures(applying IDs), but that is a seperate issue and one I am not familiar enough with.

**Comment by VGPU-Community-Drivers** [comment]
Should also be an example for users -> If you have a good Idea, feel free to submit a PR with your wished changes.
